package cn.boz.domain.ora.pojo;

import java.util.Date;
import java.math.BigDecimal;

public class DbaUsers {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.DBA_USERS.USERNAME
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.DBA_USERS.USER_ID
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private BigDecimal userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.DBA_USERS.PASSWORD
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.DBA_USERS.ACCOUNT_STATUS
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private String accountStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.DBA_USERS.LOCK_DATE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private Date lockDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.DBA_USERS.EXPIRY_DATE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private Date expiryDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.DBA_USERS.DEFAULT_TABLESPACE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private String defaultTablespace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.DBA_USERS.TEMPORARY_TABLESPACE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private String temporaryTablespace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.DBA_USERS.CREATED
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private Date created;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.DBA_USERS.PROFILE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private String profile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.DBA_USERS.INITIAL_RSRC_CONSUMER_GROUP
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private String initialRsrcConsumerGroup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.DBA_USERS.EXTERNAL_NAME
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private String externalName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.DBA_USERS.PASSWORD_VERSIONS
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private String passwordVersions;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.DBA_USERS.EDITIONS_ENABLED
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private String editionsEnabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.DBA_USERS.AUTHENTICATION_TYPE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private String authenticationType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.DBA_USERS.USERNAME
	 * @return  the value of SYS.DBA_USERS.USERNAME
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.DBA_USERS.USERNAME
	 * @param username  the value for SYS.DBA_USERS.USERNAME
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.DBA_USERS.USER_ID
	 * @return  the value of SYS.DBA_USERS.USER_ID
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public BigDecimal getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.DBA_USERS.USER_ID
	 * @param userId  the value for SYS.DBA_USERS.USER_ID
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setUserId(BigDecimal userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.DBA_USERS.PASSWORD
	 * @return  the value of SYS.DBA_USERS.PASSWORD
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.DBA_USERS.PASSWORD
	 * @param password  the value for SYS.DBA_USERS.PASSWORD
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.DBA_USERS.ACCOUNT_STATUS
	 * @return  the value of SYS.DBA_USERS.ACCOUNT_STATUS
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public String getAccountStatus() {
		return accountStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.DBA_USERS.ACCOUNT_STATUS
	 * @param accountStatus  the value for SYS.DBA_USERS.ACCOUNT_STATUS
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setAccountStatus(String accountStatus) {
		this.accountStatus = accountStatus == null ? null : accountStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.DBA_USERS.LOCK_DATE
	 * @return  the value of SYS.DBA_USERS.LOCK_DATE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public Date getLockDate() {
		return lockDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.DBA_USERS.LOCK_DATE
	 * @param lockDate  the value for SYS.DBA_USERS.LOCK_DATE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setLockDate(Date lockDate) {
		this.lockDate = lockDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.DBA_USERS.EXPIRY_DATE
	 * @return  the value of SYS.DBA_USERS.EXPIRY_DATE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public Date getExpiryDate() {
		return expiryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.DBA_USERS.EXPIRY_DATE
	 * @param expiryDate  the value for SYS.DBA_USERS.EXPIRY_DATE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.DBA_USERS.DEFAULT_TABLESPACE
	 * @return  the value of SYS.DBA_USERS.DEFAULT_TABLESPACE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public String getDefaultTablespace() {
		return defaultTablespace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.DBA_USERS.DEFAULT_TABLESPACE
	 * @param defaultTablespace  the value for SYS.DBA_USERS.DEFAULT_TABLESPACE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setDefaultTablespace(String defaultTablespace) {
		this.defaultTablespace = defaultTablespace == null ? null : defaultTablespace.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.DBA_USERS.TEMPORARY_TABLESPACE
	 * @return  the value of SYS.DBA_USERS.TEMPORARY_TABLESPACE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public String getTemporaryTablespace() {
		return temporaryTablespace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.DBA_USERS.TEMPORARY_TABLESPACE
	 * @param temporaryTablespace  the value for SYS.DBA_USERS.TEMPORARY_TABLESPACE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setTemporaryTablespace(String temporaryTablespace) {
		this.temporaryTablespace = temporaryTablespace == null ? null : temporaryTablespace.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.DBA_USERS.CREATED
	 * @return  the value of SYS.DBA_USERS.CREATED
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public Date getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.DBA_USERS.CREATED
	 * @param created  the value for SYS.DBA_USERS.CREATED
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setCreated(Date created) {
		this.created = created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.DBA_USERS.PROFILE
	 * @return  the value of SYS.DBA_USERS.PROFILE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public String getProfile() {
		return profile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.DBA_USERS.PROFILE
	 * @param profile  the value for SYS.DBA_USERS.PROFILE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setProfile(String profile) {
		this.profile = profile == null ? null : profile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.DBA_USERS.INITIAL_RSRC_CONSUMER_GROUP
	 * @return  the value of SYS.DBA_USERS.INITIAL_RSRC_CONSUMER_GROUP
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public String getInitialRsrcConsumerGroup() {
		return initialRsrcConsumerGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.DBA_USERS.INITIAL_RSRC_CONSUMER_GROUP
	 * @param initialRsrcConsumerGroup  the value for SYS.DBA_USERS.INITIAL_RSRC_CONSUMER_GROUP
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setInitialRsrcConsumerGroup(String initialRsrcConsumerGroup) {
		this.initialRsrcConsumerGroup = initialRsrcConsumerGroup == null ? null : initialRsrcConsumerGroup.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.DBA_USERS.EXTERNAL_NAME
	 * @return  the value of SYS.DBA_USERS.EXTERNAL_NAME
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public String getExternalName() {
		return externalName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.DBA_USERS.EXTERNAL_NAME
	 * @param externalName  the value for SYS.DBA_USERS.EXTERNAL_NAME
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setExternalName(String externalName) {
		this.externalName = externalName == null ? null : externalName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.DBA_USERS.PASSWORD_VERSIONS
	 * @return  the value of SYS.DBA_USERS.PASSWORD_VERSIONS
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public String getPasswordVersions() {
		return passwordVersions;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.DBA_USERS.PASSWORD_VERSIONS
	 * @param passwordVersions  the value for SYS.DBA_USERS.PASSWORD_VERSIONS
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setPasswordVersions(String passwordVersions) {
		this.passwordVersions = passwordVersions == null ? null : passwordVersions.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.DBA_USERS.EDITIONS_ENABLED
	 * @return  the value of SYS.DBA_USERS.EDITIONS_ENABLED
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public String getEditionsEnabled() {
		return editionsEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.DBA_USERS.EDITIONS_ENABLED
	 * @param editionsEnabled  the value for SYS.DBA_USERS.EDITIONS_ENABLED
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setEditionsEnabled(String editionsEnabled) {
		this.editionsEnabled = editionsEnabled == null ? null : editionsEnabled.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.DBA_USERS.AUTHENTICATION_TYPE
	 * @return  the value of SYS.DBA_USERS.AUTHENTICATION_TYPE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public String getAuthenticationType() {
		return authenticationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.DBA_USERS.AUTHENTICATION_TYPE
	 * @param authenticationType  the value for SYS.DBA_USERS.AUTHENTICATION_TYPE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setAuthenticationType(String authenticationType) {
		this.authenticationType = authenticationType == null ? null : authenticationType.trim();
	}
}