package cn.boz.domain.ora.pojo;

public class RoleSysPrivs {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.ROLE_SYS_PRIVS.ROLE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private String role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.ROLE_SYS_PRIVS.PRIVILEGE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private String privilege;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.ROLE_SYS_PRIVS.ADMIN_OPTION
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private String adminOption;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.ROLE_SYS_PRIVS.ROLE
	 * @return  the value of SYS.ROLE_SYS_PRIVS.ROLE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.ROLE_SYS_PRIVS.ROLE
	 * @param role  the value for SYS.ROLE_SYS_PRIVS.ROLE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setRole(String role) {
		this.role = role == null ? null : role.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.ROLE_SYS_PRIVS.PRIVILEGE
	 * @return  the value of SYS.ROLE_SYS_PRIVS.PRIVILEGE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public String getPrivilege() {
		return privilege;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.ROLE_SYS_PRIVS.PRIVILEGE
	 * @param privilege  the value for SYS.ROLE_SYS_PRIVS.PRIVILEGE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setPrivilege(String privilege) {
		this.privilege = privilege == null ? null : privilege.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.ROLE_SYS_PRIVS.ADMIN_OPTION
	 * @return  the value of SYS.ROLE_SYS_PRIVS.ADMIN_OPTION
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public String getAdminOption() {
		return adminOption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.ROLE_SYS_PRIVS.ADMIN_OPTION
	 * @param adminOption  the value for SYS.ROLE_SYS_PRIVS.ADMIN_OPTION
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setAdminOption(String adminOption) {
		this.adminOption = adminOption == null ? null : adminOption.trim();
	}
}