package cn.boz.domain.ora.pojo;

public class RoleRolePrivs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.ROLE_ROLE_PRIVS.ROLE
     *
     * @mbg.generated Tue Aug 28 17:06:43 CST 2018
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.ROLE_ROLE_PRIVS.GRANTED_ROLE
     *
     * @mbg.generated Tue Aug 28 17:06:43 CST 2018
     */
    private String grantedRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.ROLE_ROLE_PRIVS.ADMIN_OPTION
     *
     * @mbg.generated Tue Aug 28 17:06:43 CST 2018
     */
    private String adminOption;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.ROLE_ROLE_PRIVS.ROLE
     *
     * @return the value of SYS.ROLE_ROLE_PRIVS.ROLE
     *
     * @mbg.generated Tue Aug 28 17:06:43 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.ROLE_ROLE_PRIVS.ROLE
     *
     * @param role the value for SYS.ROLE_ROLE_PRIVS.ROLE
     *
     * @mbg.generated Tue Aug 28 17:06:43 CST 2018
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.ROLE_ROLE_PRIVS.GRANTED_ROLE
     *
     * @return the value of SYS.ROLE_ROLE_PRIVS.GRANTED_ROLE
     *
     * @mbg.generated Tue Aug 28 17:06:43 CST 2018
     */
    public String getGrantedRole() {
        return grantedRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.ROLE_ROLE_PRIVS.GRANTED_ROLE
     *
     * @param grantedRole the value for SYS.ROLE_ROLE_PRIVS.GRANTED_ROLE
     *
     * @mbg.generated Tue Aug 28 17:06:43 CST 2018
     */
    public void setGrantedRole(String grantedRole) {
        this.grantedRole = grantedRole == null ? null : grantedRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.ROLE_ROLE_PRIVS.ADMIN_OPTION
     *
     * @return the value of SYS.ROLE_ROLE_PRIVS.ADMIN_OPTION
     *
     * @mbg.generated Tue Aug 28 17:06:43 CST 2018
     */
    public String getAdminOption() {
        return adminOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.ROLE_ROLE_PRIVS.ADMIN_OPTION
     *
     * @param adminOption the value for SYS.ROLE_ROLE_PRIVS.ADMIN_OPTION
     *
     * @mbg.generated Tue Aug 28 17:06:43 CST 2018
     */
    public void setAdminOption(String adminOption) {
        this.adminOption = adminOption == null ? null : adminOption.trim();
    }
}