package cn.boz.domain.ora.pojo;

public class UserSysPrivs {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.USER_SYS_PRIVS.USERNAME
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.USER_SYS_PRIVS.PRIVILEGE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private String privilege;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SYS.USER_SYS_PRIVS.ADMIN_OPTION
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	private String adminOption;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.USER_SYS_PRIVS.USERNAME
	 * @return  the value of SYS.USER_SYS_PRIVS.USERNAME
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.USER_SYS_PRIVS.USERNAME
	 * @param username  the value for SYS.USER_SYS_PRIVS.USERNAME
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.USER_SYS_PRIVS.PRIVILEGE
	 * @return  the value of SYS.USER_SYS_PRIVS.PRIVILEGE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public String getPrivilege() {
		return privilege;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.USER_SYS_PRIVS.PRIVILEGE
	 * @param privilege  the value for SYS.USER_SYS_PRIVS.PRIVILEGE
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setPrivilege(String privilege) {
		this.privilege = privilege == null ? null : privilege.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SYS.USER_SYS_PRIVS.ADMIN_OPTION
	 * @return  the value of SYS.USER_SYS_PRIVS.ADMIN_OPTION
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public String getAdminOption() {
		return adminOption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SYS.USER_SYS_PRIVS.ADMIN_OPTION
	 * @param adminOption  the value for SYS.USER_SYS_PRIVS.ADMIN_OPTION
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	public void setAdminOption(String adminOption) {
		this.adminOption = adminOption == null ? null : adminOption.trim();
	}
}