package cn.boz.ora.mapper;

import cn.boz.domain.ora.pojo.DbaTabCols;
import cn.boz.domain.ora.pojo.DbaTabColsExample;
import cn.boz.domain.ora.pojo.DbaTabColsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbaTabColsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    long countByExample(DbaTabColsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    int deleteByExample(DbaTabColsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    int insert(DbaTabColsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    int insertSelective(DbaTabColsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    List<DbaTabColsWithBLOBs> selectByExampleWithBLOBs(DbaTabColsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    List<DbaTabCols> selectByExample(DbaTabColsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") DbaTabColsWithBLOBs record, @Param("example") DbaTabColsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") DbaTabColsWithBLOBs record, @Param("example") DbaTabColsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    int updateByExample(@Param("record") DbaTabCols record, @Param("example") DbaTabColsExample example);
}