package cn.boz.ora.mapper;

import cn.boz.domain.ora.pojo.DbaTabColumns;
import cn.boz.domain.ora.pojo.DbaTabColumnsExample;
import cn.boz.domain.ora.pojo.DbaTabColumnsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbaTabColumnsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLUMNS
     *
     * @mbg.generated Wed Sep 26 15:01:04 CST 2018
     */
    long countByExample(DbaTabColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLUMNS
     *
     * @mbg.generated Wed Sep 26 15:01:04 CST 2018
     */
    int deleteByExample(DbaTabColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLUMNS
     *
     * @mbg.generated Wed Sep 26 15:01:04 CST 2018
     */
    int insert(DbaTabColumnsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLUMNS
     *
     * @mbg.generated Wed Sep 26 15:01:04 CST 2018
     */
    int insertSelective(DbaTabColumnsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLUMNS
     *
     * @mbg.generated Wed Sep 26 15:01:04 CST 2018
     */
    List<DbaTabColumnsWithBLOBs> selectByExampleWithBLOBs(DbaTabColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLUMNS
     *
     * @mbg.generated Wed Sep 26 15:01:04 CST 2018
     */
    List<DbaTabColumns> selectByExample(DbaTabColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLUMNS
     *
     * @mbg.generated Wed Sep 26 15:01:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") DbaTabColumnsWithBLOBs record, @Param("example") DbaTabColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLUMNS
     *
     * @mbg.generated Wed Sep 26 15:01:04 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") DbaTabColumnsWithBLOBs record, @Param("example") DbaTabColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_TAB_COLUMNS
     *
     * @mbg.generated Wed Sep 26 15:01:04 CST 2018
     */
    int updateByExample(@Param("record") DbaTabColumns record, @Param("example") DbaTabColumnsExample example);
}