package cn.boz.ora.mapper;

import cn.boz.domain.ora.pojo.UserConstraints;
import cn.boz.domain.ora.pojo.UserConstraintsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserConstraintsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.USER_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:36:41 CST 2018
     */
    long countByExample(UserConstraintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.USER_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:36:41 CST 2018
     */
    int deleteByExample(UserConstraintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.USER_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:36:41 CST 2018
     */
    int insert(UserConstraints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.USER_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:36:41 CST 2018
     */
    int insertSelective(UserConstraints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.USER_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:36:41 CST 2018
     */
    List<UserConstraints> selectByExampleWithBLOBs(UserConstraintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.USER_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:36:41 CST 2018
     */
    List<UserConstraints> selectByExample(UserConstraintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.USER_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:36:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserConstraints record, @Param("example") UserConstraintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.USER_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:36:41 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") UserConstraints record, @Param("example") UserConstraintsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.USER_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:36:41 CST 2018
     */
    int updateByExample(@Param("record") UserConstraints record, @Param("example") UserConstraintsExample example);
}