package cn.boz.ora.mapper;

import cn.boz.domain.ora.pojo.RoleRolePrivs;
import cn.boz.domain.ora.pojo.RoleRolePrivsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleRolePrivsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ROLE_ROLE_PRIVS
     *
     * @mbg.generated Tue Aug 28 17:06:43 CST 2018
     */
    long countByExample(RoleRolePrivsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ROLE_ROLE_PRIVS
     *
     * @mbg.generated Tue Aug 28 17:06:43 CST 2018
     */
    int deleteByExample(RoleRolePrivsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ROLE_ROLE_PRIVS
     *
     * @mbg.generated Tue Aug 28 17:06:43 CST 2018
     */
    int insert(RoleRolePrivs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ROLE_ROLE_PRIVS
     *
     * @mbg.generated Tue Aug 28 17:06:43 CST 2018
     */
    int insertSelective(RoleRolePrivs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ROLE_ROLE_PRIVS
     *
     * @mbg.generated Tue Aug 28 17:06:43 CST 2018
     */
    List<RoleRolePrivs> selectByExample(RoleRolePrivsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ROLE_ROLE_PRIVS
     *
     * @mbg.generated Tue Aug 28 17:06:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") RoleRolePrivs record, @Param("example") RoleRolePrivsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.ROLE_ROLE_PRIVS
     *
     * @mbg.generated Tue Aug 28 17:06:43 CST 2018
     */
    int updateByExample(@Param("record") RoleRolePrivs record, @Param("example") RoleRolePrivsExample example);
}