package cn.boz.ora.mapper;

import cn.boz.domain.ora.pojo.UserSysPrivs;
import cn.boz.domain.ora.pojo.UserSysPrivsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserSysPrivsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS.USER_SYS_PRIVS
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	long countByExample(UserSysPrivsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS.USER_SYS_PRIVS
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	int deleteByExample(UserSysPrivsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS.USER_SYS_PRIVS
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	int insert(UserSysPrivs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS.USER_SYS_PRIVS
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	int insertSelective(UserSysPrivs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS.USER_SYS_PRIVS
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	List<UserSysPrivs> selectByExample(UserSysPrivsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS.USER_SYS_PRIVS
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	int updateByExampleSelective(@Param("record") UserSysPrivs record, @Param("example") UserSysPrivsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SYS.USER_SYS_PRIVS
	 * @mbg.generated  Tue Aug 28 11:39:07 CST 2018
	 */
	int updateByExample(@Param("record") UserSysPrivs record, @Param("example") UserSysPrivsExample example);
}