package cn.boz.mapper;

import cn.boz.domain.pojo.ActGeProperty;
import cn.boz.domain.pojo.ActGePropertyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActGePropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    long countByExample(ActGePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int deleteByExample(ActGePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insert(ActGeProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insertSelective(ActGeProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    List<ActGeProperty> selectByExample(ActGePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") ActGeProperty record, @Param("example") ActGePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ge_property
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExample(@Param("record") ActGeProperty record, @Param("example") ActGePropertyExample example);
}