package cn.boz.mapper;

import cn.boz.domain.pojo.ActHiVarinst;
import cn.boz.domain.pojo.ActHiVarinstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActHiVarinstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    long countByExample(ActHiVarinstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int deleteByExample(ActHiVarinstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insert(ActHiVarinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insertSelective(ActHiVarinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    List<ActHiVarinst> selectByExample(ActHiVarinstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") ActHiVarinst record, @Param("example") ActHiVarinstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_varinst
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExample(@Param("record") ActHiVarinst record, @Param("example") ActHiVarinstExample example);
}