package cn.boz.mapper;

import cn.boz.domain.pojo.ActHiActinst;
import cn.boz.domain.pojo.ActHiActinstExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActHiActinstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    long countByExample(ActHiActinstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int deleteByExample(ActHiActinstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insert(ActHiActinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insertSelective(ActHiActinst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    List<ActHiActinst> selectByExample(ActHiActinstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") ActHiActinst record, @Param("example") ActHiActinstExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_actinst
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExample(@Param("record") ActHiActinst record, @Param("example") ActHiActinstExample example);
}