package cn.boz.mapper;

import cn.boz.domain.pojo.ActHiIdentitylink;
import cn.boz.domain.pojo.ActHiIdentitylinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActHiIdentitylinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    long countByExample(ActHiIdentitylinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int deleteByExample(ActHiIdentitylinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insert(ActHiIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insertSelective(ActHiIdentitylink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    List<ActHiIdentitylink> selectByExample(ActHiIdentitylinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") ActHiIdentitylink record, @Param("example") ActHiIdentitylinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_hi_identitylink
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExample(@Param("record") ActHiIdentitylink record, @Param("example") ActHiIdentitylinkExample example);
}