package cn.boz.mapper;

import cn.boz.domain.pojo.ActReModel;
import cn.boz.domain.pojo.ActReModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActReModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_model
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    long countByExample(ActReModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_model
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int deleteByExample(ActReModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_model
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insert(ActReModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_model
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insertSelective(ActReModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_model
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    List<ActReModel> selectByExample(ActReModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_model
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") ActReModel record, @Param("example") ActReModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_model
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExample(@Param("record") ActReModel record, @Param("example") ActReModelExample example);
}