package cn.boz.mapper;

import cn.boz.domain.pojo.ActRuJob;
import cn.boz.domain.pojo.ActRuJobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActRuJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_job
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    long countByExample(ActRuJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_job
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int deleteByExample(ActRuJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_job
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insert(ActRuJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_job
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insertSelective(ActRuJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_job
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    List<ActRuJob> selectByExample(ActRuJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_job
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") ActRuJob record, @Param("example") ActRuJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_job
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExample(@Param("record") ActRuJob record, @Param("example") ActRuJobExample example);
}