package cn.boz.mapper;

import cn.boz.domain.pojo.ActRuExecution;
import cn.boz.domain.pojo.ActRuExecutionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActRuExecutionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_execution
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    long countByExample(ActRuExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_execution
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int deleteByExample(ActRuExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_execution
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insert(ActRuExecution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_execution
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insertSelective(ActRuExecution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_execution
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    List<ActRuExecution> selectByExample(ActRuExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_execution
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") ActRuExecution record, @Param("example") ActRuExecutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_execution
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExample(@Param("record") ActRuExecution record, @Param("example") ActRuExecutionExample example);
}