package cn.boz.mapper;

import cn.boz.domain.pojo.ActRuVariable;
import cn.boz.domain.pojo.ActRuVariableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActRuVariableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    long countByExample(ActRuVariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int deleteByExample(ActRuVariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insert(ActRuVariable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insertSelective(ActRuVariable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    List<ActRuVariable> selectByExample(ActRuVariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") ActRuVariable record, @Param("example") ActRuVariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_ru_variable
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExample(@Param("record") ActRuVariable record, @Param("example") ActRuVariableExample example);
}