package cn.boz.mapper;

import cn.boz.domain.pojo.ActReProcdef;
import cn.boz.domain.pojo.ActReProcdefExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActReProcdefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    long countByExample(ActReProcdefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int deleteByExample(ActReProcdefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insert(ActReProcdef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int insertSelective(ActReProcdef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    List<ActReProcdef> selectByExample(ActReProcdefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") ActReProcdef record, @Param("example") ActReProcdefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_re_procdef
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    int updateByExample(@Param("record") ActReProcdef record, @Param("example") ActReProcdefExample example);
}