package cn.boz.domain.pojo;

import java.util.Date;

public class ActHiTaskinst {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.PROC_DEF_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String procDefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.TASK_DEF_KEY_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String taskDefKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.PROC_INST_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.EXECUTION_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String executionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.NAME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.PARENT_TASK_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String parentTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.DESCRIPTION_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.OWNER_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.ASSIGNEE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String assignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.START_TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.CLAIM_TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private Date claimTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.END_TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.DURATION_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private Long duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.DELETE_REASON_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String deleteReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.PRIORITY_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.DUE_DATE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private Date dueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.FORM_KEY_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String formKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.CATEGORY_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_taskinst.TENANT_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.ID_
     *
     * @return the value of act_hi_taskinst.ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.ID_
     *
     * @param id the value for act_hi_taskinst.ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.PROC_DEF_ID_
     *
     * @return the value of act_hi_taskinst.PROC_DEF_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getProcDefId() {
        return procDefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.PROC_DEF_ID_
     *
     * @param procDefId the value for act_hi_taskinst.PROC_DEF_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setProcDefId(String procDefId) {
        this.procDefId = procDefId == null ? null : procDefId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.TASK_DEF_KEY_
     *
     * @return the value of act_hi_taskinst.TASK_DEF_KEY_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getTaskDefKey() {
        return taskDefKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.TASK_DEF_KEY_
     *
     * @param taskDefKey the value for act_hi_taskinst.TASK_DEF_KEY_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setTaskDefKey(String taskDefKey) {
        this.taskDefKey = taskDefKey == null ? null : taskDefKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.PROC_INST_ID_
     *
     * @return the value of act_hi_taskinst.PROC_INST_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.PROC_INST_ID_
     *
     * @param procInstId the value for act_hi_taskinst.PROC_INST_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.EXECUTION_ID_
     *
     * @return the value of act_hi_taskinst.EXECUTION_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getExecutionId() {
        return executionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.EXECUTION_ID_
     *
     * @param executionId the value for act_hi_taskinst.EXECUTION_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setExecutionId(String executionId) {
        this.executionId = executionId == null ? null : executionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.NAME_
     *
     * @return the value of act_hi_taskinst.NAME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.NAME_
     *
     * @param name the value for act_hi_taskinst.NAME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.PARENT_TASK_ID_
     *
     * @return the value of act_hi_taskinst.PARENT_TASK_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getParentTaskId() {
        return parentTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.PARENT_TASK_ID_
     *
     * @param parentTaskId the value for act_hi_taskinst.PARENT_TASK_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setParentTaskId(String parentTaskId) {
        this.parentTaskId = parentTaskId == null ? null : parentTaskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.DESCRIPTION_
     *
     * @return the value of act_hi_taskinst.DESCRIPTION_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.DESCRIPTION_
     *
     * @param description the value for act_hi_taskinst.DESCRIPTION_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.OWNER_
     *
     * @return the value of act_hi_taskinst.OWNER_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.OWNER_
     *
     * @param owner the value for act_hi_taskinst.OWNER_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.ASSIGNEE_
     *
     * @return the value of act_hi_taskinst.ASSIGNEE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getAssignee() {
        return assignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.ASSIGNEE_
     *
     * @param assignee the value for act_hi_taskinst.ASSIGNEE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setAssignee(String assignee) {
        this.assignee = assignee == null ? null : assignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.START_TIME_
     *
     * @return the value of act_hi_taskinst.START_TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.START_TIME_
     *
     * @param startTime the value for act_hi_taskinst.START_TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.CLAIM_TIME_
     *
     * @return the value of act_hi_taskinst.CLAIM_TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public Date getClaimTime() {
        return claimTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.CLAIM_TIME_
     *
     * @param claimTime the value for act_hi_taskinst.CLAIM_TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setClaimTime(Date claimTime) {
        this.claimTime = claimTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.END_TIME_
     *
     * @return the value of act_hi_taskinst.END_TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.END_TIME_
     *
     * @param endTime the value for act_hi_taskinst.END_TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.DURATION_
     *
     * @return the value of act_hi_taskinst.DURATION_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.DURATION_
     *
     * @param duration the value for act_hi_taskinst.DURATION_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.DELETE_REASON_
     *
     * @return the value of act_hi_taskinst.DELETE_REASON_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getDeleteReason() {
        return deleteReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.DELETE_REASON_
     *
     * @param deleteReason the value for act_hi_taskinst.DELETE_REASON_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setDeleteReason(String deleteReason) {
        this.deleteReason = deleteReason == null ? null : deleteReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.PRIORITY_
     *
     * @return the value of act_hi_taskinst.PRIORITY_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.PRIORITY_
     *
     * @param priority the value for act_hi_taskinst.PRIORITY_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.DUE_DATE_
     *
     * @return the value of act_hi_taskinst.DUE_DATE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.DUE_DATE_
     *
     * @param dueDate the value for act_hi_taskinst.DUE_DATE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.FORM_KEY_
     *
     * @return the value of act_hi_taskinst.FORM_KEY_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getFormKey() {
        return formKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.FORM_KEY_
     *
     * @param formKey the value for act_hi_taskinst.FORM_KEY_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setFormKey(String formKey) {
        this.formKey = formKey == null ? null : formKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.CATEGORY_
     *
     * @return the value of act_hi_taskinst.CATEGORY_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.CATEGORY_
     *
     * @param category the value for act_hi_taskinst.CATEGORY_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_taskinst.TENANT_ID_
     *
     * @return the value of act_hi_taskinst.TENANT_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_taskinst.TENANT_ID_
     *
     * @param tenantId the value for act_hi_taskinst.TENANT_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }
}