package cn.boz.domain.pojo;

import java.util.Date;

public class ActHiVarinst {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.PROC_INST_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.EXECUTION_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String executionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.TASK_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.NAME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.VAR_TYPE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String varType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.REV_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.BYTEARRAY_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String bytearrayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.DOUBLE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private Double doubleval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.LONG_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private Long longval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.TEXT_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.TEXT2_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String text2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.CREATE_TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_varinst.LAST_UPDATED_TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private Date lastUpdatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.ID_
     *
     * @return the value of act_hi_varinst.ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.ID_
     *
     * @param id the value for act_hi_varinst.ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.PROC_INST_ID_
     *
     * @return the value of act_hi_varinst.PROC_INST_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.PROC_INST_ID_
     *
     * @param procInstId the value for act_hi_varinst.PROC_INST_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.EXECUTION_ID_
     *
     * @return the value of act_hi_varinst.EXECUTION_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getExecutionId() {
        return executionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.EXECUTION_ID_
     *
     * @param executionId the value for act_hi_varinst.EXECUTION_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setExecutionId(String executionId) {
        this.executionId = executionId == null ? null : executionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.TASK_ID_
     *
     * @return the value of act_hi_varinst.TASK_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.TASK_ID_
     *
     * @param taskId the value for act_hi_varinst.TASK_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.NAME_
     *
     * @return the value of act_hi_varinst.NAME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.NAME_
     *
     * @param name the value for act_hi_varinst.NAME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.VAR_TYPE_
     *
     * @return the value of act_hi_varinst.VAR_TYPE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getVarType() {
        return varType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.VAR_TYPE_
     *
     * @param varType the value for act_hi_varinst.VAR_TYPE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setVarType(String varType) {
        this.varType = varType == null ? null : varType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.REV_
     *
     * @return the value of act_hi_varinst.REV_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.REV_
     *
     * @param rev the value for act_hi_varinst.REV_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.BYTEARRAY_ID_
     *
     * @return the value of act_hi_varinst.BYTEARRAY_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getBytearrayId() {
        return bytearrayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.BYTEARRAY_ID_
     *
     * @param bytearrayId the value for act_hi_varinst.BYTEARRAY_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setBytearrayId(String bytearrayId) {
        this.bytearrayId = bytearrayId == null ? null : bytearrayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.DOUBLE_
     *
     * @return the value of act_hi_varinst.DOUBLE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public Double getDoubleval() {
        return doubleval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.DOUBLE_
     *
     * @param doubleval the value for act_hi_varinst.DOUBLE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setDoubleval(Double doubleval) {
        this.doubleval = doubleval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.LONG_
     *
     * @return the value of act_hi_varinst.LONG_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public Long getLongval() {
        return longval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.LONG_
     *
     * @param longval the value for act_hi_varinst.LONG_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setLongval(Long longval) {
        this.longval = longval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.TEXT_
     *
     * @return the value of act_hi_varinst.TEXT_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.TEXT_
     *
     * @param text the value for act_hi_varinst.TEXT_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.TEXT2_
     *
     * @return the value of act_hi_varinst.TEXT2_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getText2() {
        return text2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.TEXT2_
     *
     * @param text2 the value for act_hi_varinst.TEXT2_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setText2(String text2) {
        this.text2 = text2 == null ? null : text2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.CREATE_TIME_
     *
     * @return the value of act_hi_varinst.CREATE_TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.CREATE_TIME_
     *
     * @param createTime the value for act_hi_varinst.CREATE_TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_varinst.LAST_UPDATED_TIME_
     *
     * @return the value of act_hi_varinst.LAST_UPDATED_TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public Date getLastUpdatedTime() {
        return lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_varinst.LAST_UPDATED_TIME_
     *
     * @param lastUpdatedTime the value for act_hi_varinst.LAST_UPDATED_TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }
}