package cn.boz.domain.pojo;

import java.util.Date;

public class ActHiDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.TYPE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.PROC_INST_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String procInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.EXECUTION_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String executionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.TASK_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.ACT_INST_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String actInstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.NAME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.VAR_TYPE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String varType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.REV_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.BYTEARRAY_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String bytearrayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.DOUBLE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private Double doubleval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.LONG_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private Long longval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.TEXT_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_hi_detail.TEXT2_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String text2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.ID_
     *
     * @return the value of act_hi_detail.ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.ID_
     *
     * @param id the value for act_hi_detail.ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.TYPE_
     *
     * @return the value of act_hi_detail.TYPE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.TYPE_
     *
     * @param type the value for act_hi_detail.TYPE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.PROC_INST_ID_
     *
     * @return the value of act_hi_detail.PROC_INST_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getProcInstId() {
        return procInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.PROC_INST_ID_
     *
     * @param procInstId the value for act_hi_detail.PROC_INST_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setProcInstId(String procInstId) {
        this.procInstId = procInstId == null ? null : procInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.EXECUTION_ID_
     *
     * @return the value of act_hi_detail.EXECUTION_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getExecutionId() {
        return executionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.EXECUTION_ID_
     *
     * @param executionId the value for act_hi_detail.EXECUTION_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setExecutionId(String executionId) {
        this.executionId = executionId == null ? null : executionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.TASK_ID_
     *
     * @return the value of act_hi_detail.TASK_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.TASK_ID_
     *
     * @param taskId the value for act_hi_detail.TASK_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.ACT_INST_ID_
     *
     * @return the value of act_hi_detail.ACT_INST_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getActInstId() {
        return actInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.ACT_INST_ID_
     *
     * @param actInstId the value for act_hi_detail.ACT_INST_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setActInstId(String actInstId) {
        this.actInstId = actInstId == null ? null : actInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.NAME_
     *
     * @return the value of act_hi_detail.NAME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.NAME_
     *
     * @param name the value for act_hi_detail.NAME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.VAR_TYPE_
     *
     * @return the value of act_hi_detail.VAR_TYPE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getVarType() {
        return varType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.VAR_TYPE_
     *
     * @param varType the value for act_hi_detail.VAR_TYPE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setVarType(String varType) {
        this.varType = varType == null ? null : varType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.REV_
     *
     * @return the value of act_hi_detail.REV_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.REV_
     *
     * @param rev the value for act_hi_detail.REV_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.TIME_
     *
     * @return the value of act_hi_detail.TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.TIME_
     *
     * @param time the value for act_hi_detail.TIME_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.BYTEARRAY_ID_
     *
     * @return the value of act_hi_detail.BYTEARRAY_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getBytearrayId() {
        return bytearrayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.BYTEARRAY_ID_
     *
     * @param bytearrayId the value for act_hi_detail.BYTEARRAY_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setBytearrayId(String bytearrayId) {
        this.bytearrayId = bytearrayId == null ? null : bytearrayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.DOUBLE_
     *
     * @return the value of act_hi_detail.DOUBLE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public Double getDoubleval() {
        return doubleval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.DOUBLE_
     *
     * @param doubleval the value for act_hi_detail.DOUBLE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setDoubleval(Double doubleval) {
        this.doubleval = doubleval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.LONG_
     *
     * @return the value of act_hi_detail.LONG_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public Long getLongval() {
        return longval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.LONG_
     *
     * @param longval the value for act_hi_detail.LONG_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setLongval(Long longval) {
        this.longval = longval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.TEXT_
     *
     * @return the value of act_hi_detail.TEXT_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.TEXT_
     *
     * @param text the value for act_hi_detail.TEXT_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_hi_detail.TEXT2_
     *
     * @return the value of act_hi_detail.TEXT2_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getText2() {
        return text2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_hi_detail.TEXT2_
     *
     * @param text2 the value for act_hi_detail.TEXT2_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setText2(String text2) {
        this.text2 = text2 == null ? null : text2.trim();
    }
}