package cn.boz.domain.pojo;

public class ActIdInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_info.ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_info.REV_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private Integer rev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_info.USER_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_info.TYPE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_info.KEY_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_info.VALUE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_info.PARENT_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_id_info.PASSWORD_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    private byte[] password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_info.ID_
     *
     * @return the value of act_id_info.ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_info.ID_
     *
     * @param id the value for act_id_info.ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_info.REV_
     *
     * @return the value of act_id_info.REV_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public Integer getRev() {
        return rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_info.REV_
     *
     * @param rev the value for act_id_info.REV_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setRev(Integer rev) {
        this.rev = rev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_info.USER_ID_
     *
     * @return the value of act_id_info.USER_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_info.USER_ID_
     *
     * @param userId the value for act_id_info.USER_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_info.TYPE_
     *
     * @return the value of act_id_info.TYPE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_info.TYPE_
     *
     * @param type the value for act_id_info.TYPE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_info.KEY_
     *
     * @return the value of act_id_info.KEY_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_info.KEY_
     *
     * @param key the value for act_id_info.KEY_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_info.VALUE_
     *
     * @return the value of act_id_info.VALUE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_info.VALUE_
     *
     * @param value the value for act_id_info.VALUE_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_info.PARENT_ID_
     *
     * @return the value of act_id_info.PARENT_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_info.PARENT_ID_
     *
     * @param parentId the value for act_id_info.PARENT_ID_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_id_info.PASSWORD_
     *
     * @return the value of act_id_info.PASSWORD_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public byte[] getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_id_info.PASSWORD_
     *
     * @param password the value for act_id_info.PASSWORD_
     *
     * @mbg.generated Sun Aug 26 11:58:27 CST 2018
     */
    public void setPassword(byte[] password) {
        this.password = password;
    }
}