spring:
  datasource1:
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql:///test
    username: root
    password:
  orclds:
    driverClassName: oracle.jdbc.driver.OracleDriver
    jdbcUrl: jdbc:oracle:thin:@19.131.100.226:1522:ZHSP
    username: zhspdev
    password: zhspdev
