package cn.boz.domain.ora.pojo;

public class DbaColComments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_COL_COMMENTS.OWNER
     *
     * @mbg.generated Fri Sep 21 19:40:06 CST 2018
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_COL_COMMENTS.TABLE_NAME
     *
     * @mbg.generated Fri Sep 21 19:40:06 CST 2018
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_COL_COMMENTS.COLUMN_NAME
     *
     * @mbg.generated Fri Sep 21 19:40:06 CST 2018
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_COL_COMMENTS.COMMENTS
     *
     * @mbg.generated Fri Sep 21 19:40:06 CST 2018
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_COL_COMMENTS.OWNER
     *
     * @return the value of SYS.DBA_COL_COMMENTS.OWNER
     *
     * @mbg.generated Fri Sep 21 19:40:06 CST 2018
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_COL_COMMENTS.OWNER
     *
     * @param owner the value for SYS.DBA_COL_COMMENTS.OWNER
     *
     * @mbg.generated Fri Sep 21 19:40:06 CST 2018
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_COL_COMMENTS.TABLE_NAME
     *
     * @return the value of SYS.DBA_COL_COMMENTS.TABLE_NAME
     *
     * @mbg.generated Fri Sep 21 19:40:06 CST 2018
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_COL_COMMENTS.TABLE_NAME
     *
     * @param tableName the value for SYS.DBA_COL_COMMENTS.TABLE_NAME
     *
     * @mbg.generated Fri Sep 21 19:40:06 CST 2018
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_COL_COMMENTS.COLUMN_NAME
     *
     * @return the value of SYS.DBA_COL_COMMENTS.COLUMN_NAME
     *
     * @mbg.generated Fri Sep 21 19:40:06 CST 2018
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_COL_COMMENTS.COLUMN_NAME
     *
     * @param columnName the value for SYS.DBA_COL_COMMENTS.COLUMN_NAME
     *
     * @mbg.generated Fri Sep 21 19:40:06 CST 2018
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_COL_COMMENTS.COMMENTS
     *
     * @return the value of SYS.DBA_COL_COMMENTS.COMMENTS
     *
     * @mbg.generated Fri Sep 21 19:40:06 CST 2018
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_COL_COMMENTS.COMMENTS
     *
     * @param comments the value for SYS.DBA_COL_COMMENTS.COMMENTS
     *
     * @mbg.generated Fri Sep 21 19:40:06 CST 2018
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}