package cn.boz.domain.ora.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DbaConstraintsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS.DBA_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:57:17 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS.DBA_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:57:17 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SYS.DBA_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:57:17 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:57:17 CST 2018
     */
    public DbaConstraintsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:57:17 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:57:17 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:57:17 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:57:17 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:57:17 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:57:17 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:57:17 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:57:17 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:57:17 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS.DBA_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:57:17 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS.DBA_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:57:17 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOwnerIsNull() {
            addCriterion("OWNER is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNotNull() {
            addCriterion("OWNER is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerEqualTo(String value) {
            addCriterion("OWNER =", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotEqualTo(String value) {
            addCriterion("OWNER <>", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThan(String value) {
            addCriterion("OWNER >", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("OWNER >=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThan(String value) {
            addCriterion("OWNER <", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThanOrEqualTo(String value) {
            addCriterion("OWNER <=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLike(String value) {
            addCriterion("OWNER like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotLike(String value) {
            addCriterion("OWNER not like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerIn(List<String> values) {
            addCriterion("OWNER in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotIn(List<String> values) {
            addCriterion("OWNER not in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerBetween(String value1, String value2) {
            addCriterion("OWNER between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotBetween(String value1, String value2) {
            addCriterion("OWNER not between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andConstraintNameIsNull() {
            addCriterion("CONSTRAINT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andConstraintNameIsNotNull() {
            addCriterion("CONSTRAINT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andConstraintNameEqualTo(String value) {
            addCriterion("CONSTRAINT_NAME =", value, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameNotEqualTo(String value) {
            addCriterion("CONSTRAINT_NAME <>", value, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameGreaterThan(String value) {
            addCriterion("CONSTRAINT_NAME >", value, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameGreaterThanOrEqualTo(String value) {
            addCriterion("CONSTRAINT_NAME >=", value, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameLessThan(String value) {
            addCriterion("CONSTRAINT_NAME <", value, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameLessThanOrEqualTo(String value) {
            addCriterion("CONSTRAINT_NAME <=", value, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameLike(String value) {
            addCriterion("CONSTRAINT_NAME like", value, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameNotLike(String value) {
            addCriterion("CONSTRAINT_NAME not like", value, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameIn(List<String> values) {
            addCriterion("CONSTRAINT_NAME in", values, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameNotIn(List<String> values) {
            addCriterion("CONSTRAINT_NAME not in", values, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameBetween(String value1, String value2) {
            addCriterion("CONSTRAINT_NAME between", value1, value2, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintNameNotBetween(String value1, String value2) {
            addCriterion("CONSTRAINT_NAME not between", value1, value2, "constraintName");
            return (Criteria) this;
        }

        public Criteria andConstraintTypeIsNull() {
            addCriterion("CONSTRAINT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andConstraintTypeIsNotNull() {
            addCriterion("CONSTRAINT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andConstraintTypeEqualTo(String value) {
            addCriterion("CONSTRAINT_TYPE =", value, "constraintType");
            return (Criteria) this;
        }

        public Criteria andConstraintTypeNotEqualTo(String value) {
            addCriterion("CONSTRAINT_TYPE <>", value, "constraintType");
            return (Criteria) this;
        }

        public Criteria andConstraintTypeGreaterThan(String value) {
            addCriterion("CONSTRAINT_TYPE >", value, "constraintType");
            return (Criteria) this;
        }

        public Criteria andConstraintTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CONSTRAINT_TYPE >=", value, "constraintType");
            return (Criteria) this;
        }

        public Criteria andConstraintTypeLessThan(String value) {
            addCriterion("CONSTRAINT_TYPE <", value, "constraintType");
            return (Criteria) this;
        }

        public Criteria andConstraintTypeLessThanOrEqualTo(String value) {
            addCriterion("CONSTRAINT_TYPE <=", value, "constraintType");
            return (Criteria) this;
        }

        public Criteria andConstraintTypeLike(String value) {
            addCriterion("CONSTRAINT_TYPE like", value, "constraintType");
            return (Criteria) this;
        }

        public Criteria andConstraintTypeNotLike(String value) {
            addCriterion("CONSTRAINT_TYPE not like", value, "constraintType");
            return (Criteria) this;
        }

        public Criteria andConstraintTypeIn(List<String> values) {
            addCriterion("CONSTRAINT_TYPE in", values, "constraintType");
            return (Criteria) this;
        }

        public Criteria andConstraintTypeNotIn(List<String> values) {
            addCriterion("CONSTRAINT_TYPE not in", values, "constraintType");
            return (Criteria) this;
        }

        public Criteria andConstraintTypeBetween(String value1, String value2) {
            addCriterion("CONSTRAINT_TYPE between", value1, value2, "constraintType");
            return (Criteria) this;
        }

        public Criteria andConstraintTypeNotBetween(String value1, String value2) {
            addCriterion("CONSTRAINT_TYPE not between", value1, value2, "constraintType");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNull() {
            addCriterion("TABLE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNotNull() {
            addCriterion("TABLE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTableNameEqualTo(String value) {
            addCriterion("TABLE_NAME =", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotEqualTo(String value) {
            addCriterion("TABLE_NAME <>", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThan(String value) {
            addCriterion("TABLE_NAME >", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_NAME >=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThan(String value) {
            addCriterion("TABLE_NAME <", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThanOrEqualTo(String value) {
            addCriterion("TABLE_NAME <=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLike(String value) {
            addCriterion("TABLE_NAME like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotLike(String value) {
            addCriterion("TABLE_NAME not like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameIn(List<String> values) {
            addCriterion("TABLE_NAME in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotIn(List<String> values) {
            addCriterion("TABLE_NAME not in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameBetween(String value1, String value2) {
            addCriterion("TABLE_NAME between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotBetween(String value1, String value2) {
            addCriterion("TABLE_NAME not between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andSearchConditionVcIsNull() {
            addCriterion("SEARCH_CONDITION_VC is null");
            return (Criteria) this;
        }

        public Criteria andSearchConditionVcIsNotNull() {
            addCriterion("SEARCH_CONDITION_VC is not null");
            return (Criteria) this;
        }

        public Criteria andSearchConditionVcEqualTo(String value) {
            addCriterion("SEARCH_CONDITION_VC =", value, "searchConditionVc");
            return (Criteria) this;
        }

        public Criteria andSearchConditionVcNotEqualTo(String value) {
            addCriterion("SEARCH_CONDITION_VC <>", value, "searchConditionVc");
            return (Criteria) this;
        }

        public Criteria andSearchConditionVcGreaterThan(String value) {
            addCriterion("SEARCH_CONDITION_VC >", value, "searchConditionVc");
            return (Criteria) this;
        }

        public Criteria andSearchConditionVcGreaterThanOrEqualTo(String value) {
            addCriterion("SEARCH_CONDITION_VC >=", value, "searchConditionVc");
            return (Criteria) this;
        }

        public Criteria andSearchConditionVcLessThan(String value) {
            addCriterion("SEARCH_CONDITION_VC <", value, "searchConditionVc");
            return (Criteria) this;
        }

        public Criteria andSearchConditionVcLessThanOrEqualTo(String value) {
            addCriterion("SEARCH_CONDITION_VC <=", value, "searchConditionVc");
            return (Criteria) this;
        }

        public Criteria andSearchConditionVcLike(String value) {
            addCriterion("SEARCH_CONDITION_VC like", value, "searchConditionVc");
            return (Criteria) this;
        }

        public Criteria andSearchConditionVcNotLike(String value) {
            addCriterion("SEARCH_CONDITION_VC not like", value, "searchConditionVc");
            return (Criteria) this;
        }

        public Criteria andSearchConditionVcIn(List<String> values) {
            addCriterion("SEARCH_CONDITION_VC in", values, "searchConditionVc");
            return (Criteria) this;
        }

        public Criteria andSearchConditionVcNotIn(List<String> values) {
            addCriterion("SEARCH_CONDITION_VC not in", values, "searchConditionVc");
            return (Criteria) this;
        }

        public Criteria andSearchConditionVcBetween(String value1, String value2) {
            addCriterion("SEARCH_CONDITION_VC between", value1, value2, "searchConditionVc");
            return (Criteria) this;
        }

        public Criteria andSearchConditionVcNotBetween(String value1, String value2) {
            addCriterion("SEARCH_CONDITION_VC not between", value1, value2, "searchConditionVc");
            return (Criteria) this;
        }

        public Criteria andROwnerIsNull() {
            addCriterion("R_OWNER is null");
            return (Criteria) this;
        }

        public Criteria andROwnerIsNotNull() {
            addCriterion("R_OWNER is not null");
            return (Criteria) this;
        }

        public Criteria andROwnerEqualTo(String value) {
            addCriterion("R_OWNER =", value, "rOwner");
            return (Criteria) this;
        }

        public Criteria andROwnerNotEqualTo(String value) {
            addCriterion("R_OWNER <>", value, "rOwner");
            return (Criteria) this;
        }

        public Criteria andROwnerGreaterThan(String value) {
            addCriterion("R_OWNER >", value, "rOwner");
            return (Criteria) this;
        }

        public Criteria andROwnerGreaterThanOrEqualTo(String value) {
            addCriterion("R_OWNER >=", value, "rOwner");
            return (Criteria) this;
        }

        public Criteria andROwnerLessThan(String value) {
            addCriterion("R_OWNER <", value, "rOwner");
            return (Criteria) this;
        }

        public Criteria andROwnerLessThanOrEqualTo(String value) {
            addCriterion("R_OWNER <=", value, "rOwner");
            return (Criteria) this;
        }

        public Criteria andROwnerLike(String value) {
            addCriterion("R_OWNER like", value, "rOwner");
            return (Criteria) this;
        }

        public Criteria andROwnerNotLike(String value) {
            addCriterion("R_OWNER not like", value, "rOwner");
            return (Criteria) this;
        }

        public Criteria andROwnerIn(List<String> values) {
            addCriterion("R_OWNER in", values, "rOwner");
            return (Criteria) this;
        }

        public Criteria andROwnerNotIn(List<String> values) {
            addCriterion("R_OWNER not in", values, "rOwner");
            return (Criteria) this;
        }

        public Criteria andROwnerBetween(String value1, String value2) {
            addCriterion("R_OWNER between", value1, value2, "rOwner");
            return (Criteria) this;
        }

        public Criteria andROwnerNotBetween(String value1, String value2) {
            addCriterion("R_OWNER not between", value1, value2, "rOwner");
            return (Criteria) this;
        }

        public Criteria andRConstraintNameIsNull() {
            addCriterion("R_CONSTRAINT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andRConstraintNameIsNotNull() {
            addCriterion("R_CONSTRAINT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andRConstraintNameEqualTo(String value) {
            addCriterion("R_CONSTRAINT_NAME =", value, "rConstraintName");
            return (Criteria) this;
        }

        public Criteria andRConstraintNameNotEqualTo(String value) {
            addCriterion("R_CONSTRAINT_NAME <>", value, "rConstraintName");
            return (Criteria) this;
        }

        public Criteria andRConstraintNameGreaterThan(String value) {
            addCriterion("R_CONSTRAINT_NAME >", value, "rConstraintName");
            return (Criteria) this;
        }

        public Criteria andRConstraintNameGreaterThanOrEqualTo(String value) {
            addCriterion("R_CONSTRAINT_NAME >=", value, "rConstraintName");
            return (Criteria) this;
        }

        public Criteria andRConstraintNameLessThan(String value) {
            addCriterion("R_CONSTRAINT_NAME <", value, "rConstraintName");
            return (Criteria) this;
        }

        public Criteria andRConstraintNameLessThanOrEqualTo(String value) {
            addCriterion("R_CONSTRAINT_NAME <=", value, "rConstraintName");
            return (Criteria) this;
        }

        public Criteria andRConstraintNameLike(String value) {
            addCriterion("R_CONSTRAINT_NAME like", value, "rConstraintName");
            return (Criteria) this;
        }

        public Criteria andRConstraintNameNotLike(String value) {
            addCriterion("R_CONSTRAINT_NAME not like", value, "rConstraintName");
            return (Criteria) this;
        }

        public Criteria andRConstraintNameIn(List<String> values) {
            addCriterion("R_CONSTRAINT_NAME in", values, "rConstraintName");
            return (Criteria) this;
        }

        public Criteria andRConstraintNameNotIn(List<String> values) {
            addCriterion("R_CONSTRAINT_NAME not in", values, "rConstraintName");
            return (Criteria) this;
        }

        public Criteria andRConstraintNameBetween(String value1, String value2) {
            addCriterion("R_CONSTRAINT_NAME between", value1, value2, "rConstraintName");
            return (Criteria) this;
        }

        public Criteria andRConstraintNameNotBetween(String value1, String value2) {
            addCriterion("R_CONSTRAINT_NAME not between", value1, value2, "rConstraintName");
            return (Criteria) this;
        }

        public Criteria andDeleteRuleIsNull() {
            addCriterion("DELETE_RULE is null");
            return (Criteria) this;
        }

        public Criteria andDeleteRuleIsNotNull() {
            addCriterion("DELETE_RULE is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteRuleEqualTo(String value) {
            addCriterion("DELETE_RULE =", value, "deleteRule");
            return (Criteria) this;
        }

        public Criteria andDeleteRuleNotEqualTo(String value) {
            addCriterion("DELETE_RULE <>", value, "deleteRule");
            return (Criteria) this;
        }

        public Criteria andDeleteRuleGreaterThan(String value) {
            addCriterion("DELETE_RULE >", value, "deleteRule");
            return (Criteria) this;
        }

        public Criteria andDeleteRuleGreaterThanOrEqualTo(String value) {
            addCriterion("DELETE_RULE >=", value, "deleteRule");
            return (Criteria) this;
        }

        public Criteria andDeleteRuleLessThan(String value) {
            addCriterion("DELETE_RULE <", value, "deleteRule");
            return (Criteria) this;
        }

        public Criteria andDeleteRuleLessThanOrEqualTo(String value) {
            addCriterion("DELETE_RULE <=", value, "deleteRule");
            return (Criteria) this;
        }

        public Criteria andDeleteRuleLike(String value) {
            addCriterion("DELETE_RULE like", value, "deleteRule");
            return (Criteria) this;
        }

        public Criteria andDeleteRuleNotLike(String value) {
            addCriterion("DELETE_RULE not like", value, "deleteRule");
            return (Criteria) this;
        }

        public Criteria andDeleteRuleIn(List<String> values) {
            addCriterion("DELETE_RULE in", values, "deleteRule");
            return (Criteria) this;
        }

        public Criteria andDeleteRuleNotIn(List<String> values) {
            addCriterion("DELETE_RULE not in", values, "deleteRule");
            return (Criteria) this;
        }

        public Criteria andDeleteRuleBetween(String value1, String value2) {
            addCriterion("DELETE_RULE between", value1, value2, "deleteRule");
            return (Criteria) this;
        }

        public Criteria andDeleteRuleNotBetween(String value1, String value2) {
            addCriterion("DELETE_RULE not between", value1, value2, "deleteRule");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andDeferrableIsNull() {
            addCriterion("DEFERRABLE is null");
            return (Criteria) this;
        }

        public Criteria andDeferrableIsNotNull() {
            addCriterion("DEFERRABLE is not null");
            return (Criteria) this;
        }

        public Criteria andDeferrableEqualTo(String value) {
            addCriterion("DEFERRABLE =", value, "deferrable");
            return (Criteria) this;
        }

        public Criteria andDeferrableNotEqualTo(String value) {
            addCriterion("DEFERRABLE <>", value, "deferrable");
            return (Criteria) this;
        }

        public Criteria andDeferrableGreaterThan(String value) {
            addCriterion("DEFERRABLE >", value, "deferrable");
            return (Criteria) this;
        }

        public Criteria andDeferrableGreaterThanOrEqualTo(String value) {
            addCriterion("DEFERRABLE >=", value, "deferrable");
            return (Criteria) this;
        }

        public Criteria andDeferrableLessThan(String value) {
            addCriterion("DEFERRABLE <", value, "deferrable");
            return (Criteria) this;
        }

        public Criteria andDeferrableLessThanOrEqualTo(String value) {
            addCriterion("DEFERRABLE <=", value, "deferrable");
            return (Criteria) this;
        }

        public Criteria andDeferrableLike(String value) {
            addCriterion("DEFERRABLE like", value, "deferrable");
            return (Criteria) this;
        }

        public Criteria andDeferrableNotLike(String value) {
            addCriterion("DEFERRABLE not like", value, "deferrable");
            return (Criteria) this;
        }

        public Criteria andDeferrableIn(List<String> values) {
            addCriterion("DEFERRABLE in", values, "deferrable");
            return (Criteria) this;
        }

        public Criteria andDeferrableNotIn(List<String> values) {
            addCriterion("DEFERRABLE not in", values, "deferrable");
            return (Criteria) this;
        }

        public Criteria andDeferrableBetween(String value1, String value2) {
            addCriterion("DEFERRABLE between", value1, value2, "deferrable");
            return (Criteria) this;
        }

        public Criteria andDeferrableNotBetween(String value1, String value2) {
            addCriterion("DEFERRABLE not between", value1, value2, "deferrable");
            return (Criteria) this;
        }

        public Criteria andDeferredIsNull() {
            addCriterion("DEFERRED is null");
            return (Criteria) this;
        }

        public Criteria andDeferredIsNotNull() {
            addCriterion("DEFERRED is not null");
            return (Criteria) this;
        }

        public Criteria andDeferredEqualTo(String value) {
            addCriterion("DEFERRED =", value, "deferred");
            return (Criteria) this;
        }

        public Criteria andDeferredNotEqualTo(String value) {
            addCriterion("DEFERRED <>", value, "deferred");
            return (Criteria) this;
        }

        public Criteria andDeferredGreaterThan(String value) {
            addCriterion("DEFERRED >", value, "deferred");
            return (Criteria) this;
        }

        public Criteria andDeferredGreaterThanOrEqualTo(String value) {
            addCriterion("DEFERRED >=", value, "deferred");
            return (Criteria) this;
        }

        public Criteria andDeferredLessThan(String value) {
            addCriterion("DEFERRED <", value, "deferred");
            return (Criteria) this;
        }

        public Criteria andDeferredLessThanOrEqualTo(String value) {
            addCriterion("DEFERRED <=", value, "deferred");
            return (Criteria) this;
        }

        public Criteria andDeferredLike(String value) {
            addCriterion("DEFERRED like", value, "deferred");
            return (Criteria) this;
        }

        public Criteria andDeferredNotLike(String value) {
            addCriterion("DEFERRED not like", value, "deferred");
            return (Criteria) this;
        }

        public Criteria andDeferredIn(List<String> values) {
            addCriterion("DEFERRED in", values, "deferred");
            return (Criteria) this;
        }

        public Criteria andDeferredNotIn(List<String> values) {
            addCriterion("DEFERRED not in", values, "deferred");
            return (Criteria) this;
        }

        public Criteria andDeferredBetween(String value1, String value2) {
            addCriterion("DEFERRED between", value1, value2, "deferred");
            return (Criteria) this;
        }

        public Criteria andDeferredNotBetween(String value1, String value2) {
            addCriterion("DEFERRED not between", value1, value2, "deferred");
            return (Criteria) this;
        }

        public Criteria andValidatedIsNull() {
            addCriterion("VALIDATED is null");
            return (Criteria) this;
        }

        public Criteria andValidatedIsNotNull() {
            addCriterion("VALIDATED is not null");
            return (Criteria) this;
        }

        public Criteria andValidatedEqualTo(String value) {
            addCriterion("VALIDATED =", value, "validated");
            return (Criteria) this;
        }

        public Criteria andValidatedNotEqualTo(String value) {
            addCriterion("VALIDATED <>", value, "validated");
            return (Criteria) this;
        }

        public Criteria andValidatedGreaterThan(String value) {
            addCriterion("VALIDATED >", value, "validated");
            return (Criteria) this;
        }

        public Criteria andValidatedGreaterThanOrEqualTo(String value) {
            addCriterion("VALIDATED >=", value, "validated");
            return (Criteria) this;
        }

        public Criteria andValidatedLessThan(String value) {
            addCriterion("VALIDATED <", value, "validated");
            return (Criteria) this;
        }

        public Criteria andValidatedLessThanOrEqualTo(String value) {
            addCriterion("VALIDATED <=", value, "validated");
            return (Criteria) this;
        }

        public Criteria andValidatedLike(String value) {
            addCriterion("VALIDATED like", value, "validated");
            return (Criteria) this;
        }

        public Criteria andValidatedNotLike(String value) {
            addCriterion("VALIDATED not like", value, "validated");
            return (Criteria) this;
        }

        public Criteria andValidatedIn(List<String> values) {
            addCriterion("VALIDATED in", values, "validated");
            return (Criteria) this;
        }

        public Criteria andValidatedNotIn(List<String> values) {
            addCriterion("VALIDATED not in", values, "validated");
            return (Criteria) this;
        }

        public Criteria andValidatedBetween(String value1, String value2) {
            addCriterion("VALIDATED between", value1, value2, "validated");
            return (Criteria) this;
        }

        public Criteria andValidatedNotBetween(String value1, String value2) {
            addCriterion("VALIDATED not between", value1, value2, "validated");
            return (Criteria) this;
        }

        public Criteria andGeneratedIsNull() {
            addCriterion("GENERATED is null");
            return (Criteria) this;
        }

        public Criteria andGeneratedIsNotNull() {
            addCriterion("GENERATED is not null");
            return (Criteria) this;
        }

        public Criteria andGeneratedEqualTo(String value) {
            addCriterion("GENERATED =", value, "generated");
            return (Criteria) this;
        }

        public Criteria andGeneratedNotEqualTo(String value) {
            addCriterion("GENERATED <>", value, "generated");
            return (Criteria) this;
        }

        public Criteria andGeneratedGreaterThan(String value) {
            addCriterion("GENERATED >", value, "generated");
            return (Criteria) this;
        }

        public Criteria andGeneratedGreaterThanOrEqualTo(String value) {
            addCriterion("GENERATED >=", value, "generated");
            return (Criteria) this;
        }

        public Criteria andGeneratedLessThan(String value) {
            addCriterion("GENERATED <", value, "generated");
            return (Criteria) this;
        }

        public Criteria andGeneratedLessThanOrEqualTo(String value) {
            addCriterion("GENERATED <=", value, "generated");
            return (Criteria) this;
        }

        public Criteria andGeneratedLike(String value) {
            addCriterion("GENERATED like", value, "generated");
            return (Criteria) this;
        }

        public Criteria andGeneratedNotLike(String value) {
            addCriterion("GENERATED not like", value, "generated");
            return (Criteria) this;
        }

        public Criteria andGeneratedIn(List<String> values) {
            addCriterion("GENERATED in", values, "generated");
            return (Criteria) this;
        }

        public Criteria andGeneratedNotIn(List<String> values) {
            addCriterion("GENERATED not in", values, "generated");
            return (Criteria) this;
        }

        public Criteria andGeneratedBetween(String value1, String value2) {
            addCriterion("GENERATED between", value1, value2, "generated");
            return (Criteria) this;
        }

        public Criteria andGeneratedNotBetween(String value1, String value2) {
            addCriterion("GENERATED not between", value1, value2, "generated");
            return (Criteria) this;
        }

        public Criteria andBadIsNull() {
            addCriterion("BAD is null");
            return (Criteria) this;
        }

        public Criteria andBadIsNotNull() {
            addCriterion("BAD is not null");
            return (Criteria) this;
        }

        public Criteria andBadEqualTo(String value) {
            addCriterion("BAD =", value, "bad");
            return (Criteria) this;
        }

        public Criteria andBadNotEqualTo(String value) {
            addCriterion("BAD <>", value, "bad");
            return (Criteria) this;
        }

        public Criteria andBadGreaterThan(String value) {
            addCriterion("BAD >", value, "bad");
            return (Criteria) this;
        }

        public Criteria andBadGreaterThanOrEqualTo(String value) {
            addCriterion("BAD >=", value, "bad");
            return (Criteria) this;
        }

        public Criteria andBadLessThan(String value) {
            addCriterion("BAD <", value, "bad");
            return (Criteria) this;
        }

        public Criteria andBadLessThanOrEqualTo(String value) {
            addCriterion("BAD <=", value, "bad");
            return (Criteria) this;
        }

        public Criteria andBadLike(String value) {
            addCriterion("BAD like", value, "bad");
            return (Criteria) this;
        }

        public Criteria andBadNotLike(String value) {
            addCriterion("BAD not like", value, "bad");
            return (Criteria) this;
        }

        public Criteria andBadIn(List<String> values) {
            addCriterion("BAD in", values, "bad");
            return (Criteria) this;
        }

        public Criteria andBadNotIn(List<String> values) {
            addCriterion("BAD not in", values, "bad");
            return (Criteria) this;
        }

        public Criteria andBadBetween(String value1, String value2) {
            addCriterion("BAD between", value1, value2, "bad");
            return (Criteria) this;
        }

        public Criteria andBadNotBetween(String value1, String value2) {
            addCriterion("BAD not between", value1, value2, "bad");
            return (Criteria) this;
        }

        public Criteria andRelyIsNull() {
            addCriterion("RELY is null");
            return (Criteria) this;
        }

        public Criteria andRelyIsNotNull() {
            addCriterion("RELY is not null");
            return (Criteria) this;
        }

        public Criteria andRelyEqualTo(String value) {
            addCriterion("RELY =", value, "rely");
            return (Criteria) this;
        }

        public Criteria andRelyNotEqualTo(String value) {
            addCriterion("RELY <>", value, "rely");
            return (Criteria) this;
        }

        public Criteria andRelyGreaterThan(String value) {
            addCriterion("RELY >", value, "rely");
            return (Criteria) this;
        }

        public Criteria andRelyGreaterThanOrEqualTo(String value) {
            addCriterion("RELY >=", value, "rely");
            return (Criteria) this;
        }

        public Criteria andRelyLessThan(String value) {
            addCriterion("RELY <", value, "rely");
            return (Criteria) this;
        }

        public Criteria andRelyLessThanOrEqualTo(String value) {
            addCriterion("RELY <=", value, "rely");
            return (Criteria) this;
        }

        public Criteria andRelyLike(String value) {
            addCriterion("RELY like", value, "rely");
            return (Criteria) this;
        }

        public Criteria andRelyNotLike(String value) {
            addCriterion("RELY not like", value, "rely");
            return (Criteria) this;
        }

        public Criteria andRelyIn(List<String> values) {
            addCriterion("RELY in", values, "rely");
            return (Criteria) this;
        }

        public Criteria andRelyNotIn(List<String> values) {
            addCriterion("RELY not in", values, "rely");
            return (Criteria) this;
        }

        public Criteria andRelyBetween(String value1, String value2) {
            addCriterion("RELY between", value1, value2, "rely");
            return (Criteria) this;
        }

        public Criteria andRelyNotBetween(String value1, String value2) {
            addCriterion("RELY not between", value1, value2, "rely");
            return (Criteria) this;
        }

        public Criteria andLastChangeIsNull() {
            addCriterion("LAST_CHANGE is null");
            return (Criteria) this;
        }

        public Criteria andLastChangeIsNotNull() {
            addCriterion("LAST_CHANGE is not null");
            return (Criteria) this;
        }

        public Criteria andLastChangeEqualTo(Date value) {
            addCriterion("LAST_CHANGE =", value, "lastChange");
            return (Criteria) this;
        }

        public Criteria andLastChangeNotEqualTo(Date value) {
            addCriterion("LAST_CHANGE <>", value, "lastChange");
            return (Criteria) this;
        }

        public Criteria andLastChangeGreaterThan(Date value) {
            addCriterion("LAST_CHANGE >", value, "lastChange");
            return (Criteria) this;
        }

        public Criteria andLastChangeGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_CHANGE >=", value, "lastChange");
            return (Criteria) this;
        }

        public Criteria andLastChangeLessThan(Date value) {
            addCriterion("LAST_CHANGE <", value, "lastChange");
            return (Criteria) this;
        }

        public Criteria andLastChangeLessThanOrEqualTo(Date value) {
            addCriterion("LAST_CHANGE <=", value, "lastChange");
            return (Criteria) this;
        }

        public Criteria andLastChangeIn(List<Date> values) {
            addCriterion("LAST_CHANGE in", values, "lastChange");
            return (Criteria) this;
        }

        public Criteria andLastChangeNotIn(List<Date> values) {
            addCriterion("LAST_CHANGE not in", values, "lastChange");
            return (Criteria) this;
        }

        public Criteria andLastChangeBetween(Date value1, Date value2) {
            addCriterion("LAST_CHANGE between", value1, value2, "lastChange");
            return (Criteria) this;
        }

        public Criteria andLastChangeNotBetween(Date value1, Date value2) {
            addCriterion("LAST_CHANGE not between", value1, value2, "lastChange");
            return (Criteria) this;
        }

        public Criteria andIndexOwnerIsNull() {
            addCriterion("INDEX_OWNER is null");
            return (Criteria) this;
        }

        public Criteria andIndexOwnerIsNotNull() {
            addCriterion("INDEX_OWNER is not null");
            return (Criteria) this;
        }

        public Criteria andIndexOwnerEqualTo(String value) {
            addCriterion("INDEX_OWNER =", value, "indexOwner");
            return (Criteria) this;
        }

        public Criteria andIndexOwnerNotEqualTo(String value) {
            addCriterion("INDEX_OWNER <>", value, "indexOwner");
            return (Criteria) this;
        }

        public Criteria andIndexOwnerGreaterThan(String value) {
            addCriterion("INDEX_OWNER >", value, "indexOwner");
            return (Criteria) this;
        }

        public Criteria andIndexOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("INDEX_OWNER >=", value, "indexOwner");
            return (Criteria) this;
        }

        public Criteria andIndexOwnerLessThan(String value) {
            addCriterion("INDEX_OWNER <", value, "indexOwner");
            return (Criteria) this;
        }

        public Criteria andIndexOwnerLessThanOrEqualTo(String value) {
            addCriterion("INDEX_OWNER <=", value, "indexOwner");
            return (Criteria) this;
        }

        public Criteria andIndexOwnerLike(String value) {
            addCriterion("INDEX_OWNER like", value, "indexOwner");
            return (Criteria) this;
        }

        public Criteria andIndexOwnerNotLike(String value) {
            addCriterion("INDEX_OWNER not like", value, "indexOwner");
            return (Criteria) this;
        }

        public Criteria andIndexOwnerIn(List<String> values) {
            addCriterion("INDEX_OWNER in", values, "indexOwner");
            return (Criteria) this;
        }

        public Criteria andIndexOwnerNotIn(List<String> values) {
            addCriterion("INDEX_OWNER not in", values, "indexOwner");
            return (Criteria) this;
        }

        public Criteria andIndexOwnerBetween(String value1, String value2) {
            addCriterion("INDEX_OWNER between", value1, value2, "indexOwner");
            return (Criteria) this;
        }

        public Criteria andIndexOwnerNotBetween(String value1, String value2) {
            addCriterion("INDEX_OWNER not between", value1, value2, "indexOwner");
            return (Criteria) this;
        }

        public Criteria andIndexNameIsNull() {
            addCriterion("INDEX_NAME is null");
            return (Criteria) this;
        }

        public Criteria andIndexNameIsNotNull() {
            addCriterion("INDEX_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andIndexNameEqualTo(String value) {
            addCriterion("INDEX_NAME =", value, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameNotEqualTo(String value) {
            addCriterion("INDEX_NAME <>", value, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameGreaterThan(String value) {
            addCriterion("INDEX_NAME >", value, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameGreaterThanOrEqualTo(String value) {
            addCriterion("INDEX_NAME >=", value, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameLessThan(String value) {
            addCriterion("INDEX_NAME <", value, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameLessThanOrEqualTo(String value) {
            addCriterion("INDEX_NAME <=", value, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameLike(String value) {
            addCriterion("INDEX_NAME like", value, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameNotLike(String value) {
            addCriterion("INDEX_NAME not like", value, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameIn(List<String> values) {
            addCriterion("INDEX_NAME in", values, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameNotIn(List<String> values) {
            addCriterion("INDEX_NAME not in", values, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameBetween(String value1, String value2) {
            addCriterion("INDEX_NAME between", value1, value2, "indexName");
            return (Criteria) this;
        }

        public Criteria andIndexNameNotBetween(String value1, String value2) {
            addCriterion("INDEX_NAME not between", value1, value2, "indexName");
            return (Criteria) this;
        }

        public Criteria andInvalidIsNull() {
            addCriterion("INVALID is null");
            return (Criteria) this;
        }

        public Criteria andInvalidIsNotNull() {
            addCriterion("INVALID is not null");
            return (Criteria) this;
        }

        public Criteria andInvalidEqualTo(String value) {
            addCriterion("INVALID =", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotEqualTo(String value) {
            addCriterion("INVALID <>", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidGreaterThan(String value) {
            addCriterion("INVALID >", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidGreaterThanOrEqualTo(String value) {
            addCriterion("INVALID >=", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLessThan(String value) {
            addCriterion("INVALID <", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLessThanOrEqualTo(String value) {
            addCriterion("INVALID <=", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidLike(String value) {
            addCriterion("INVALID like", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotLike(String value) {
            addCriterion("INVALID not like", value, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidIn(List<String> values) {
            addCriterion("INVALID in", values, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotIn(List<String> values) {
            addCriterion("INVALID not in", values, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidBetween(String value1, String value2) {
            addCriterion("INVALID between", value1, value2, "invalid");
            return (Criteria) this;
        }

        public Criteria andInvalidNotBetween(String value1, String value2) {
            addCriterion("INVALID not between", value1, value2, "invalid");
            return (Criteria) this;
        }

        public Criteria andViewRelatedIsNull() {
            addCriterion("VIEW_RELATED is null");
            return (Criteria) this;
        }

        public Criteria andViewRelatedIsNotNull() {
            addCriterion("VIEW_RELATED is not null");
            return (Criteria) this;
        }

        public Criteria andViewRelatedEqualTo(String value) {
            addCriterion("VIEW_RELATED =", value, "viewRelated");
            return (Criteria) this;
        }

        public Criteria andViewRelatedNotEqualTo(String value) {
            addCriterion("VIEW_RELATED <>", value, "viewRelated");
            return (Criteria) this;
        }

        public Criteria andViewRelatedGreaterThan(String value) {
            addCriterion("VIEW_RELATED >", value, "viewRelated");
            return (Criteria) this;
        }

        public Criteria andViewRelatedGreaterThanOrEqualTo(String value) {
            addCriterion("VIEW_RELATED >=", value, "viewRelated");
            return (Criteria) this;
        }

        public Criteria andViewRelatedLessThan(String value) {
            addCriterion("VIEW_RELATED <", value, "viewRelated");
            return (Criteria) this;
        }

        public Criteria andViewRelatedLessThanOrEqualTo(String value) {
            addCriterion("VIEW_RELATED <=", value, "viewRelated");
            return (Criteria) this;
        }

        public Criteria andViewRelatedLike(String value) {
            addCriterion("VIEW_RELATED like", value, "viewRelated");
            return (Criteria) this;
        }

        public Criteria andViewRelatedNotLike(String value) {
            addCriterion("VIEW_RELATED not like", value, "viewRelated");
            return (Criteria) this;
        }

        public Criteria andViewRelatedIn(List<String> values) {
            addCriterion("VIEW_RELATED in", values, "viewRelated");
            return (Criteria) this;
        }

        public Criteria andViewRelatedNotIn(List<String> values) {
            addCriterion("VIEW_RELATED not in", values, "viewRelated");
            return (Criteria) this;
        }

        public Criteria andViewRelatedBetween(String value1, String value2) {
            addCriterion("VIEW_RELATED between", value1, value2, "viewRelated");
            return (Criteria) this;
        }

        public Criteria andViewRelatedNotBetween(String value1, String value2) {
            addCriterion("VIEW_RELATED not between", value1, value2, "viewRelated");
            return (Criteria) this;
        }

        public Criteria andOriginConIdIsNull() {
            addCriterion("ORIGIN_CON_ID is null");
            return (Criteria) this;
        }

        public Criteria andOriginConIdIsNotNull() {
            addCriterion("ORIGIN_CON_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOriginConIdEqualTo(BigDecimal value) {
            addCriterion("ORIGIN_CON_ID =", value, "originConId");
            return (Criteria) this;
        }

        public Criteria andOriginConIdNotEqualTo(BigDecimal value) {
            addCriterion("ORIGIN_CON_ID <>", value, "originConId");
            return (Criteria) this;
        }

        public Criteria andOriginConIdGreaterThan(BigDecimal value) {
            addCriterion("ORIGIN_CON_ID >", value, "originConId");
            return (Criteria) this;
        }

        public Criteria andOriginConIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ORIGIN_CON_ID >=", value, "originConId");
            return (Criteria) this;
        }

        public Criteria andOriginConIdLessThan(BigDecimal value) {
            addCriterion("ORIGIN_CON_ID <", value, "originConId");
            return (Criteria) this;
        }

        public Criteria andOriginConIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ORIGIN_CON_ID <=", value, "originConId");
            return (Criteria) this;
        }

        public Criteria andOriginConIdIn(List<BigDecimal> values) {
            addCriterion("ORIGIN_CON_ID in", values, "originConId");
            return (Criteria) this;
        }

        public Criteria andOriginConIdNotIn(List<BigDecimal> values) {
            addCriterion("ORIGIN_CON_ID not in", values, "originConId");
            return (Criteria) this;
        }

        public Criteria andOriginConIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORIGIN_CON_ID between", value1, value2, "originConId");
            return (Criteria) this;
        }

        public Criteria andOriginConIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORIGIN_CON_ID not between", value1, value2, "originConId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS.DBA_CONSTRAINTS
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 26 11:57:17 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS.DBA_CONSTRAINTS
     *
     * @mbg.generated Wed Sep 26 11:57:17 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}