package cn.boz.domain.ora.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class DbaTabCols {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.OWNER
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.TABLE_NAME
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.COLUMN_NAME
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.DATA_TYPE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.DATA_TYPE_MOD
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String dataTypeMod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.DATA_TYPE_OWNER
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String dataTypeOwner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.DATA_LENGTH
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private BigDecimal dataLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.DATA_PRECISION
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private BigDecimal dataPrecision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.DATA_SCALE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private BigDecimal dataScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.NULLABLE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String nullable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.COLUMN_ID
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private BigDecimal columnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.DEFAULT_LENGTH
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private BigDecimal defaultLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.NUM_DISTINCT
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private BigDecimal numDistinct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.DENSITY
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private BigDecimal density;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.NUM_NULLS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private BigDecimal numNulls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.NUM_BUCKETS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private BigDecimal numBuckets;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.LAST_ANALYZED
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private Date lastAnalyzed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.SAMPLE_SIZE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private BigDecimal sampleSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.CHARACTER_SET_NAME
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String characterSetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.CHAR_COL_DECL_LENGTH
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private BigDecimal charColDeclLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.GLOBAL_STATS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String globalStats;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.USER_STATS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String userStats;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.AVG_COL_LEN
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private BigDecimal avgColLen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.CHAR_LENGTH
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private BigDecimal charLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.CHAR_USED
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String charUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.V80_FMT_IMAGE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String v80FmtImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.DATA_UPGRADED
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String dataUpgraded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.HIDDEN_COLUMN
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String hiddenColumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.VIRTUAL_COLUMN
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String virtualColumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.SEGMENT_COLUMN_ID
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private BigDecimal segmentColumnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.INTERNAL_COLUMN_ID
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private BigDecimal internalColumnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.HISTOGRAM
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String histogram;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.QUALIFIED_COL_NAME
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String qualifiedColName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.USER_GENERATED
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String userGenerated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.DEFAULT_ON_NULL
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String defaultOnNull;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.IDENTITY_COLUMN
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String identityColumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.SENSITIVE_COLUMN
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String sensitiveColumn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.EVALUATION_EDITION
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String evaluationEdition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.UNUSABLE_BEFORE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String unusableBefore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.UNUSABLE_BEGINNING
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String unusableBeginning;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.OWNER
     *
     * @return the value of SYS.DBA_TAB_COLS.OWNER
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.OWNER
     *
     * @param owner the value for SYS.DBA_TAB_COLS.OWNER
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.TABLE_NAME
     *
     * @return the value of SYS.DBA_TAB_COLS.TABLE_NAME
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.TABLE_NAME
     *
     * @param tableName the value for SYS.DBA_TAB_COLS.TABLE_NAME
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.COLUMN_NAME
     *
     * @return the value of SYS.DBA_TAB_COLS.COLUMN_NAME
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.COLUMN_NAME
     *
     * @param columnName the value for SYS.DBA_TAB_COLS.COLUMN_NAME
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.DATA_TYPE
     *
     * @return the value of SYS.DBA_TAB_COLS.DATA_TYPE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.DATA_TYPE
     *
     * @param dataType the value for SYS.DBA_TAB_COLS.DATA_TYPE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.DATA_TYPE_MOD
     *
     * @return the value of SYS.DBA_TAB_COLS.DATA_TYPE_MOD
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getDataTypeMod() {
        return dataTypeMod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.DATA_TYPE_MOD
     *
     * @param dataTypeMod the value for SYS.DBA_TAB_COLS.DATA_TYPE_MOD
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setDataTypeMod(String dataTypeMod) {
        this.dataTypeMod = dataTypeMod == null ? null : dataTypeMod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.DATA_TYPE_OWNER
     *
     * @return the value of SYS.DBA_TAB_COLS.DATA_TYPE_OWNER
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getDataTypeOwner() {
        return dataTypeOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.DATA_TYPE_OWNER
     *
     * @param dataTypeOwner the value for SYS.DBA_TAB_COLS.DATA_TYPE_OWNER
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setDataTypeOwner(String dataTypeOwner) {
        this.dataTypeOwner = dataTypeOwner == null ? null : dataTypeOwner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.DATA_LENGTH
     *
     * @return the value of SYS.DBA_TAB_COLS.DATA_LENGTH
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public BigDecimal getDataLength() {
        return dataLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.DATA_LENGTH
     *
     * @param dataLength the value for SYS.DBA_TAB_COLS.DATA_LENGTH
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setDataLength(BigDecimal dataLength) {
        this.dataLength = dataLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.DATA_PRECISION
     *
     * @return the value of SYS.DBA_TAB_COLS.DATA_PRECISION
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public BigDecimal getDataPrecision() {
        return dataPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.DATA_PRECISION
     *
     * @param dataPrecision the value for SYS.DBA_TAB_COLS.DATA_PRECISION
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setDataPrecision(BigDecimal dataPrecision) {
        this.dataPrecision = dataPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.DATA_SCALE
     *
     * @return the value of SYS.DBA_TAB_COLS.DATA_SCALE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public BigDecimal getDataScale() {
        return dataScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.DATA_SCALE
     *
     * @param dataScale the value for SYS.DBA_TAB_COLS.DATA_SCALE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setDataScale(BigDecimal dataScale) {
        this.dataScale = dataScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.NULLABLE
     *
     * @return the value of SYS.DBA_TAB_COLS.NULLABLE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getNullable() {
        return nullable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.NULLABLE
     *
     * @param nullable the value for SYS.DBA_TAB_COLS.NULLABLE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setNullable(String nullable) {
        this.nullable = nullable == null ? null : nullable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.COLUMN_ID
     *
     * @return the value of SYS.DBA_TAB_COLS.COLUMN_ID
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public BigDecimal getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.COLUMN_ID
     *
     * @param columnId the value for SYS.DBA_TAB_COLS.COLUMN_ID
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setColumnId(BigDecimal columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.DEFAULT_LENGTH
     *
     * @return the value of SYS.DBA_TAB_COLS.DEFAULT_LENGTH
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public BigDecimal getDefaultLength() {
        return defaultLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.DEFAULT_LENGTH
     *
     * @param defaultLength the value for SYS.DBA_TAB_COLS.DEFAULT_LENGTH
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setDefaultLength(BigDecimal defaultLength) {
        this.defaultLength = defaultLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.NUM_DISTINCT
     *
     * @return the value of SYS.DBA_TAB_COLS.NUM_DISTINCT
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public BigDecimal getNumDistinct() {
        return numDistinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.NUM_DISTINCT
     *
     * @param numDistinct the value for SYS.DBA_TAB_COLS.NUM_DISTINCT
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setNumDistinct(BigDecimal numDistinct) {
        this.numDistinct = numDistinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.DENSITY
     *
     * @return the value of SYS.DBA_TAB_COLS.DENSITY
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public BigDecimal getDensity() {
        return density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.DENSITY
     *
     * @param density the value for SYS.DBA_TAB_COLS.DENSITY
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setDensity(BigDecimal density) {
        this.density = density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.NUM_NULLS
     *
     * @return the value of SYS.DBA_TAB_COLS.NUM_NULLS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public BigDecimal getNumNulls() {
        return numNulls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.NUM_NULLS
     *
     * @param numNulls the value for SYS.DBA_TAB_COLS.NUM_NULLS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setNumNulls(BigDecimal numNulls) {
        this.numNulls = numNulls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.NUM_BUCKETS
     *
     * @return the value of SYS.DBA_TAB_COLS.NUM_BUCKETS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public BigDecimal getNumBuckets() {
        return numBuckets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.NUM_BUCKETS
     *
     * @param numBuckets the value for SYS.DBA_TAB_COLS.NUM_BUCKETS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setNumBuckets(BigDecimal numBuckets) {
        this.numBuckets = numBuckets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.LAST_ANALYZED
     *
     * @return the value of SYS.DBA_TAB_COLS.LAST_ANALYZED
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public Date getLastAnalyzed() {
        return lastAnalyzed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.LAST_ANALYZED
     *
     * @param lastAnalyzed the value for SYS.DBA_TAB_COLS.LAST_ANALYZED
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setLastAnalyzed(Date lastAnalyzed) {
        this.lastAnalyzed = lastAnalyzed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.SAMPLE_SIZE
     *
     * @return the value of SYS.DBA_TAB_COLS.SAMPLE_SIZE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public BigDecimal getSampleSize() {
        return sampleSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.SAMPLE_SIZE
     *
     * @param sampleSize the value for SYS.DBA_TAB_COLS.SAMPLE_SIZE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setSampleSize(BigDecimal sampleSize) {
        this.sampleSize = sampleSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.CHARACTER_SET_NAME
     *
     * @return the value of SYS.DBA_TAB_COLS.CHARACTER_SET_NAME
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getCharacterSetName() {
        return characterSetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.CHARACTER_SET_NAME
     *
     * @param characterSetName the value for SYS.DBA_TAB_COLS.CHARACTER_SET_NAME
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setCharacterSetName(String characterSetName) {
        this.characterSetName = characterSetName == null ? null : characterSetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.CHAR_COL_DECL_LENGTH
     *
     * @return the value of SYS.DBA_TAB_COLS.CHAR_COL_DECL_LENGTH
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public BigDecimal getCharColDeclLength() {
        return charColDeclLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.CHAR_COL_DECL_LENGTH
     *
     * @param charColDeclLength the value for SYS.DBA_TAB_COLS.CHAR_COL_DECL_LENGTH
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setCharColDeclLength(BigDecimal charColDeclLength) {
        this.charColDeclLength = charColDeclLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.GLOBAL_STATS
     *
     * @return the value of SYS.DBA_TAB_COLS.GLOBAL_STATS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getGlobalStats() {
        return globalStats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.GLOBAL_STATS
     *
     * @param globalStats the value for SYS.DBA_TAB_COLS.GLOBAL_STATS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setGlobalStats(String globalStats) {
        this.globalStats = globalStats == null ? null : globalStats.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.USER_STATS
     *
     * @return the value of SYS.DBA_TAB_COLS.USER_STATS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getUserStats() {
        return userStats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.USER_STATS
     *
     * @param userStats the value for SYS.DBA_TAB_COLS.USER_STATS
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setUserStats(String userStats) {
        this.userStats = userStats == null ? null : userStats.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.AVG_COL_LEN
     *
     * @return the value of SYS.DBA_TAB_COLS.AVG_COL_LEN
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public BigDecimal getAvgColLen() {
        return avgColLen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.AVG_COL_LEN
     *
     * @param avgColLen the value for SYS.DBA_TAB_COLS.AVG_COL_LEN
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setAvgColLen(BigDecimal avgColLen) {
        this.avgColLen = avgColLen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.CHAR_LENGTH
     *
     * @return the value of SYS.DBA_TAB_COLS.CHAR_LENGTH
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public BigDecimal getCharLength() {
        return charLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.CHAR_LENGTH
     *
     * @param charLength the value for SYS.DBA_TAB_COLS.CHAR_LENGTH
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setCharLength(BigDecimal charLength) {
        this.charLength = charLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.CHAR_USED
     *
     * @return the value of SYS.DBA_TAB_COLS.CHAR_USED
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getCharUsed() {
        return charUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.CHAR_USED
     *
     * @param charUsed the value for SYS.DBA_TAB_COLS.CHAR_USED
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setCharUsed(String charUsed) {
        this.charUsed = charUsed == null ? null : charUsed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.V80_FMT_IMAGE
     *
     * @return the value of SYS.DBA_TAB_COLS.V80_FMT_IMAGE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getV80FmtImage() {
        return v80FmtImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.V80_FMT_IMAGE
     *
     * @param v80FmtImage the value for SYS.DBA_TAB_COLS.V80_FMT_IMAGE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setV80FmtImage(String v80FmtImage) {
        this.v80FmtImage = v80FmtImage == null ? null : v80FmtImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.DATA_UPGRADED
     *
     * @return the value of SYS.DBA_TAB_COLS.DATA_UPGRADED
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getDataUpgraded() {
        return dataUpgraded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.DATA_UPGRADED
     *
     * @param dataUpgraded the value for SYS.DBA_TAB_COLS.DATA_UPGRADED
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setDataUpgraded(String dataUpgraded) {
        this.dataUpgraded = dataUpgraded == null ? null : dataUpgraded.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.HIDDEN_COLUMN
     *
     * @return the value of SYS.DBA_TAB_COLS.HIDDEN_COLUMN
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getHiddenColumn() {
        return hiddenColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.HIDDEN_COLUMN
     *
     * @param hiddenColumn the value for SYS.DBA_TAB_COLS.HIDDEN_COLUMN
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setHiddenColumn(String hiddenColumn) {
        this.hiddenColumn = hiddenColumn == null ? null : hiddenColumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.VIRTUAL_COLUMN
     *
     * @return the value of SYS.DBA_TAB_COLS.VIRTUAL_COLUMN
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getVirtualColumn() {
        return virtualColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.VIRTUAL_COLUMN
     *
     * @param virtualColumn the value for SYS.DBA_TAB_COLS.VIRTUAL_COLUMN
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setVirtualColumn(String virtualColumn) {
        this.virtualColumn = virtualColumn == null ? null : virtualColumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.SEGMENT_COLUMN_ID
     *
     * @return the value of SYS.DBA_TAB_COLS.SEGMENT_COLUMN_ID
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public BigDecimal getSegmentColumnId() {
        return segmentColumnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.SEGMENT_COLUMN_ID
     *
     * @param segmentColumnId the value for SYS.DBA_TAB_COLS.SEGMENT_COLUMN_ID
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setSegmentColumnId(BigDecimal segmentColumnId) {
        this.segmentColumnId = segmentColumnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.INTERNAL_COLUMN_ID
     *
     * @return the value of SYS.DBA_TAB_COLS.INTERNAL_COLUMN_ID
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public BigDecimal getInternalColumnId() {
        return internalColumnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.INTERNAL_COLUMN_ID
     *
     * @param internalColumnId the value for SYS.DBA_TAB_COLS.INTERNAL_COLUMN_ID
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setInternalColumnId(BigDecimal internalColumnId) {
        this.internalColumnId = internalColumnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.HISTOGRAM
     *
     * @return the value of SYS.DBA_TAB_COLS.HISTOGRAM
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getHistogram() {
        return histogram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.HISTOGRAM
     *
     * @param histogram the value for SYS.DBA_TAB_COLS.HISTOGRAM
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setHistogram(String histogram) {
        this.histogram = histogram == null ? null : histogram.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.QUALIFIED_COL_NAME
     *
     * @return the value of SYS.DBA_TAB_COLS.QUALIFIED_COL_NAME
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getQualifiedColName() {
        return qualifiedColName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.QUALIFIED_COL_NAME
     *
     * @param qualifiedColName the value for SYS.DBA_TAB_COLS.QUALIFIED_COL_NAME
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setQualifiedColName(String qualifiedColName) {
        this.qualifiedColName = qualifiedColName == null ? null : qualifiedColName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.USER_GENERATED
     *
     * @return the value of SYS.DBA_TAB_COLS.USER_GENERATED
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getUserGenerated() {
        return userGenerated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.USER_GENERATED
     *
     * @param userGenerated the value for SYS.DBA_TAB_COLS.USER_GENERATED
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setUserGenerated(String userGenerated) {
        this.userGenerated = userGenerated == null ? null : userGenerated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.DEFAULT_ON_NULL
     *
     * @return the value of SYS.DBA_TAB_COLS.DEFAULT_ON_NULL
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getDefaultOnNull() {
        return defaultOnNull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.DEFAULT_ON_NULL
     *
     * @param defaultOnNull the value for SYS.DBA_TAB_COLS.DEFAULT_ON_NULL
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setDefaultOnNull(String defaultOnNull) {
        this.defaultOnNull = defaultOnNull == null ? null : defaultOnNull.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.IDENTITY_COLUMN
     *
     * @return the value of SYS.DBA_TAB_COLS.IDENTITY_COLUMN
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getIdentityColumn() {
        return identityColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.IDENTITY_COLUMN
     *
     * @param identityColumn the value for SYS.DBA_TAB_COLS.IDENTITY_COLUMN
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setIdentityColumn(String identityColumn) {
        this.identityColumn = identityColumn == null ? null : identityColumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.SENSITIVE_COLUMN
     *
     * @return the value of SYS.DBA_TAB_COLS.SENSITIVE_COLUMN
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getSensitiveColumn() {
        return sensitiveColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.SENSITIVE_COLUMN
     *
     * @param sensitiveColumn the value for SYS.DBA_TAB_COLS.SENSITIVE_COLUMN
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setSensitiveColumn(String sensitiveColumn) {
        this.sensitiveColumn = sensitiveColumn == null ? null : sensitiveColumn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.EVALUATION_EDITION
     *
     * @return the value of SYS.DBA_TAB_COLS.EVALUATION_EDITION
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getEvaluationEdition() {
        return evaluationEdition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.EVALUATION_EDITION
     *
     * @param evaluationEdition the value for SYS.DBA_TAB_COLS.EVALUATION_EDITION
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setEvaluationEdition(String evaluationEdition) {
        this.evaluationEdition = evaluationEdition == null ? null : evaluationEdition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.UNUSABLE_BEFORE
     *
     * @return the value of SYS.DBA_TAB_COLS.UNUSABLE_BEFORE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getUnusableBefore() {
        return unusableBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.UNUSABLE_BEFORE
     *
     * @param unusableBefore the value for SYS.DBA_TAB_COLS.UNUSABLE_BEFORE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setUnusableBefore(String unusableBefore) {
        this.unusableBefore = unusableBefore == null ? null : unusableBefore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.UNUSABLE_BEGINNING
     *
     * @return the value of SYS.DBA_TAB_COLS.UNUSABLE_BEGINNING
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getUnusableBeginning() {
        return unusableBeginning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.UNUSABLE_BEGINNING
     *
     * @param unusableBeginning the value for SYS.DBA_TAB_COLS.UNUSABLE_BEGINNING
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setUnusableBeginning(String unusableBeginning) {
        this.unusableBeginning = unusableBeginning == null ? null : unusableBeginning.trim();
    }
}