package cn.boz.domain.ora.pojo;

public class DbaTabColsWithBLOBs extends DbaTabCols {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.DATA_DEFAULT
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private String dataDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.LOW_VALUE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private byte[] lowValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS.DBA_TAB_COLS.HIGH_VALUE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    private byte[] highValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.DATA_DEFAULT
     *
     * @return the value of SYS.DBA_TAB_COLS.DATA_DEFAULT
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public String getDataDefault() {
        return dataDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.DATA_DEFAULT
     *
     * @param dataDefault the value for SYS.DBA_TAB_COLS.DATA_DEFAULT
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setDataDefault(String dataDefault) {
        this.dataDefault = dataDefault == null ? null : dataDefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.LOW_VALUE
     *
     * @return the value of SYS.DBA_TAB_COLS.LOW_VALUE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public byte[] getLowValue() {
        return lowValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.LOW_VALUE
     *
     * @param lowValue the value for SYS.DBA_TAB_COLS.LOW_VALUE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setLowValue(byte[] lowValue) {
        this.lowValue = lowValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS.DBA_TAB_COLS.HIGH_VALUE
     *
     * @return the value of SYS.DBA_TAB_COLS.HIGH_VALUE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public byte[] getHighValue() {
        return highValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS.DBA_TAB_COLS.HIGH_VALUE
     *
     * @param highValue the value for SYS.DBA_TAB_COLS.HIGH_VALUE
     *
     * @mbg.generated Tue Sep 25 10:49:42 CST 2018
     */
    public void setHighValue(byte[] highValue) {
        this.highValue = highValue;
    }
}