package cn.boz.domain.ora.pojo;

import java.math.BigDecimal;

public class Jay {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZHSPDEV.JAY.ID
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZHSPDEV.JAY.NAME
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZHSPDEV.JAY.SALARY
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	private BigDecimal salary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZHSPDEV.JAY.CV
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	private BigDecimal cv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZHSPDEV.JAY.SAL2
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	private BigDecimal sal2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ZHSPDEV.JAY.descs
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	private String descs;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZHSPDEV.JAY.ID
	 * @return  the value of ZHSPDEV.JAY.ID
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZHSPDEV.JAY.ID
	 * @param id  the value for ZHSPDEV.JAY.ID
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZHSPDEV.JAY.NAME
	 * @return  the value of ZHSPDEV.JAY.NAME
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZHSPDEV.JAY.NAME
	 * @param name  the value for ZHSPDEV.JAY.NAME
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZHSPDEV.JAY.SALARY
	 * @return  the value of ZHSPDEV.JAY.SALARY
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	public BigDecimal getSalary() {
		return salary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZHSPDEV.JAY.SALARY
	 * @param salary  the value for ZHSPDEV.JAY.SALARY
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	public void setSalary(BigDecimal salary) {
		this.salary = salary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZHSPDEV.JAY.CV
	 * @return  the value of ZHSPDEV.JAY.CV
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	public BigDecimal getCv() {
		return cv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZHSPDEV.JAY.CV
	 * @param cv  the value for ZHSPDEV.JAY.CV
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	public void setCv(BigDecimal cv) {
		this.cv = cv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZHSPDEV.JAY.SAL2
	 * @return  the value of ZHSPDEV.JAY.SAL2
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	public BigDecimal getSal2() {
		return sal2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZHSPDEV.JAY.SAL2
	 * @param sal2  the value for ZHSPDEV.JAY.SAL2
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	public void setSal2(BigDecimal sal2) {
		this.sal2 = sal2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ZHSPDEV.JAY.descs
	 * @return  the value of ZHSPDEV.JAY.descs
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	public String getDescs() {
		return descs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ZHSPDEV.JAY.descs
	 * @param descs  the value for ZHSPDEV.JAY.descs
	 * @mbg.generated  Thu Sep 27 11:05:34 CST 2018
	 */
	public void setDescs(String descs) {
		this.descs = descs == null ? null : descs.trim();
	}
}